package com.progrexion.bcm.common.exceptions;

public enum BCMModuleExceptionEnum {
	
	BCM_MODULE_EXCEPTION("BCM-500", "Unknown BCM Module Exception", 500),
		
	//Common
	REMOTE_SYSTEM_EXCEPTION("BCM-001", "RemoteSystemException: An exception occured calling a remote system", 500),
	INVALID_DATE_FORMAT_YYYY_MM_DD("BCM-002", "Expected date format yyyy-MM-dd", 400),
	DB_EXCEPTION("BCM-003", "DataBase Exception happened", 500),
	UNSUPPORTED_VENDOR("BCM-004", "Unsupported Vendor", 400),
	DESTINATION_TYPE_INVALID("BCM-005", "Message Destination Type is invalid", 400),	
	BCM_API_INVALID_INPUT("BCM-006", "Invalid input parameter(s)", 400),
	BCM_API_INVALID_REQUEST("BCM-007", "Invalid Request", 400),
	
	//Custoemr Master 	
	CUSTOMER_MASTER_CLIENT_ERROR("BCM-008", "Customer Master Proxy Client Error", 400),
	CUSTOMER_MASTER_SERVER_ERROR("BCM-009", "Customer Master Proxy Server Error", 500),
	CUSTOMER_MASTER_400("BCM-010",Constants.CUSTOMER_MASTER_NOT_FOUND_CONS,400),
	CUSTOMER_MASTER_404("BCM-011",Constants.CUSTOMER_MASTER_NOT_FOUND_CONS,404),
	CUSTOMER_MASTER_409("BCM-012",Constants.CUSTOMER_MASTER_NOT_FOUND_CONS,409),
	CUSTOMER_MASTER_500("BCM-013",Constants.CUSTOMER_MASTER_NOT_FOUND_CONS,500),
	CUSTOMER_MASTER_503("BCM-014",Constants.CUSTOMER_MASTER_NOT_FOUND_CONS,503),
	CUSTOMER_MASTER_500_BCM("BCM-015",Constants.CUSTOMER_MASTER_NOT_FOUND_CONS+" - Remote System Exception",500),

	
	//RentTrack
	RENTTRACK_CLIENT_ERROR("BCM-400-RT", "RentTrack Client Error: Bad Request", 400),
	RENTTRACK_CLIENT_ERROR_CONFLICT("BCM-409-RT", "RentTrack Client Error: Conflict", 409),
	RENTTRACK_CLIENT_ERROR_NO_CONTENT("BCM-204-RT", "No content", 204),
	RENTTRACK_SERVER_ERROR("BCM-500-RT", "RentTrack Server Error: Internal Server Error", 500),
	RENTTRACK_CLIENT_ERROR_401("BCM-401-RT", "The access token provided has expired", 401),

	//Access Token Creation
	ACCESS_TOKEN_400("BCM-101",Constants.ACCESS_TOKEN_CONS,400),
	ACCESS_TOKEN_401("BCM-102",Constants.ACCESS_TOKEN_CONS,401),
	ACCESS_TOKEN_415("BCM-103",Constants.ACCESS_TOKEN_CONS,415),
	ACCESS_TOKEN_500("BCM-104",Constants.ACCESS_TOKEN_CONS,500),
	ACCESS_TOKEN_503("BCM-105",Constants.ACCESS_TOKEN_CONS,503),
	
	
	
	//Access Token Creation
	PARTNER_TOKEN_400("BCM-106",Constants.PARTNER_TOKEN_CONS,400),
	PARTNER_TOKEN_401("BCM-107",Constants.PARTNER_TOKEN_CONS,401),
	PARTNER_TOKEN_415("BCM-108",Constants.PARTNER_TOKEN_CONS,415),
	PARTNER_TOKEN_500("BCM-109",Constants.PARTNER_TOKEN_CONS,500),
	PARTNER_TOKEN_503("BCM-110",Constants.PARTNER_TOKEN_CONS,503),
	
	
	//Refresh Token Creation for Create tenant
	CREATE_TENANT_REFRESH_TOKEN_400("BCM-111",Constants.CREATE_TENANT_REFRESH_TOKEN_CONS,400),
	CREATE_TENANT_REFRESH_TOKEN_401("BCM-112",Constants.CREATE_TENANT_REFRESH_TOKEN_CONS,401),
	CREATE_TENANT_REFRESH_TOKEN_415("BCM-113",Constants.CREATE_TENANT_REFRESH_TOKEN_CONS,415),
	CREATE_TENANT_REFRESH_TOKEN_500("BCM-114",Constants.CREATE_TENANT_REFRESH_TOKEN_CONS,500),
	CREATE_TENANT_REFRESH_TOKEN_503("BCM-115",Constants.CREATE_TENANT_REFRESH_TOKEN_CONS,503),
	
	//Create tenant
	CREATE_TENANT_400("BCM-116",Constants.CREATE_TENANT_CONS,400),
	CREATE_TENANT_409("BCM-117",Constants.CREATE_TENANT_CONS,409),
	CREATE_TENANT_500("BCM-118",Constants.CREATE_TENANT_CONS,500),
	CREATE_TENANT_BCM_EXCEPTION("BCM-119","Unable to Create Tenant User - Remote System Exception",500),
	
	
	CUSTOMER_INFO_ALREADY_EXISTS("BCM-120", "Customer already exists in BCM", 409),
	CUSTOMER_INFO_NOT_FOUND("BCM-121", "Customer information not found", 404),
	TENANT_USER_NOT_CREATED("BCM-156",Constants.TENANT_USER_NOT_CREATED,400),
	
	PATCH_TENANT_USER_400("BCM-122",Constants.PATCH_TENANT_USER_CONS,400),
	PATCH_TENANT_USER_500("BCM-123",Constants.PATCH_TENANT_USER_CONS,500),
	
	
	
	
	
	//Subscription
	SUBSCRIPTION_400("BCM-124",Constants.SUBSCRIPTION_CONS,400),
	SUBSCRIPTION_409("BCM-125",Constants.SUBSCRIPTION_CONS,409),
	SUBSCRIPTION_500("BCM-126",Constants.SUBSCRIPTION_CONS,500),
	SUBSCRIPTION_ALREADY_AVAILABLE("BCM-127", "Subscription Already Exists", 400),
	
	
	//Refresh Token Creation for Create tenant
	SUBSCRIPTION_REFRESH_TOKEN_400("BCM-128",Constants.SUBSCRIPTION_REFRESH_TOKEN_CONS,400),
	SUBSCRIPTION_REFRESH_TOKEN_401("BCM-129",Constants.SUBSCRIPTION_REFRESH_TOKEN_CONS,401),
	SUBSCRIPTION_REFRESH_TOKEN_415("BCM-130",Constants.SUBSCRIPTION_REFRESH_TOKEN_CONS,415),
	SUBSCRIPTION_REFRESH_TOKEN_500("BCM-131",Constants.SUBSCRIPTION_REFRESH_TOKEN_CONS,500),
	SUBSCRIPTION_REFRESH_TOKEN_503("BCM-132",Constants.SUBSCRIPTION_REFRESH_TOKEN_CONS,503),
	
	
	ACCESS_TOKEN_BCM_EXCEPTION("BCM-133","Unable to Create Access Token while Creating tenant User - Remote System Exception",500),
	PARTNER_TOKEN_BCM_EXCEPTION("BCM-134","Unable to Create Partner Token while Creating tenant User - Remote System Exception",500),
	CREATE_TENANT_REFRESH_TOKEN_BCM_EXCEPTION("BCM-135","Unable to Create Refresh Token while Creating tenant User - Remote System Exception",500),
	PATCH_TENANT_USER_BCM_EXCEPTION("BCM-136","Unable to Update DOB while creating Tenant User - Remote System Exception",500),
	SUBSCRIPTION_REFRESH_TOKEN_BCM_EXCEPTION("BCM-137","Unable to Create Refresh Token while Creating Subscription - Remote System Exception",500),
	SUBSCRIPTION_BCM_EXCEPTION("BCM-138","Unable to Create Subscription while creating Tenant User - Remote System Exception",500),
	
	SUBSCRIPTION_INVALID_PROPERTY("BCM-139", "Invalid Subscription details for the customer brand", 400),
	
	PATCH_TENANT_USER_401("BCM-141",Constants.PATCH_TENANT_USER_CONS,401),
	SUBSCRIPTION_401("BCM-142","Unable to Create Subscription for the user",401),
	CUSTOMER_SUBSCRIPTION_FAILED("BCM-143", "user creation not completed successfully", 400),
  
	SUBSCRIPTIONS_GET_ALL_ACTIVE_204("BCM-144", "Cannot find active subscriptions", 400),
	SUBSCRIPTIONS_GET_ALL_ACTIVE_500("BCM-145", "Cannot find active subscriptions - Remote System Exception", 500),
	SUBSCRIPTIONS_GET_ALL_ACTIVE_500_BCM("BCM-146", "Cannot find active subscriptions - Internal Server Error", 500),
	
	SUBSCRIPTIONS_DELETE_404("BCM-147", "Unable to cancel subscription - Subsription not found", 400),
	SUBSCRIPTIONS_DELETE_500("BCM-148", "Unable to cancel subscription - Remote System Exception", 500),
	SUBSCRIPTIONS_DELETE_500_BCM("BCM-149", "Unable to cancel subscription - Internal Server Error", 500),
	
	GET_SUBSCRIPTIONS_REFRESH_TOKEN_400("BCM-150",Constants.GET_SUBSCRIPTIONS_REFRESH_TOKEN_CONS,400),
	GET_SUBSCRIPTIONS_REFRESH_TOKEN_401("BCM-151",Constants.GET_SUBSCRIPTIONS_REFRESH_TOKEN_CONS,401),
	GET_SUBSCRIPTIONS_REFRESH_TOKEN_415("BCM-152",Constants.GET_SUBSCRIPTIONS_REFRESH_TOKEN_CONS,415),
	GET_SUBSCRIPTIONS_REFRESH_TOKEN_500("BCM-153",Constants.GET_SUBSCRIPTIONS_REFRESH_TOKEN_CONS,500),
	GET_SUBSCRIPTIONS_REFRESH_TOKEN_503("BCM-154",Constants.GET_SUBSCRIPTIONS_REFRESH_TOKEN_CONS,503),
	GET_SUBSCRIPTIONS_REFRESH_TOKEN_BCM_EXCEPTION("BCM-155",Constants.GET_SUBSCRIPTIONS_REFRESH_TOKEN_CONS,503),
	
	GET_SUBSCRIPTIONS_500("BCM-155",Constants.GET_SUBSCRIPTIONS_CONS,500),
	GET_SUBSCRIPTIONS_BCM_EXCEPTION("BCM-156","Unable to verify Subscription - Remote System Exception",500),
	UNABLE_TO_PARSE_MESSAGE_BCM_MESSAGING_EXCEPTION("BCM-1000", "Unable to parse message", 500),
	UNKNOWN_ERROR_BCM_MESSAGING_EXCEPTION("BCM-1001", "An unknown error occurred", 500),
	CANNOT_FIND_CUSTOMER_BCM_MESSAGING_EXCEPTION("BCM-1002", "Cannot find Customer in BCM", 500),
	NO_ACTIVE_SUBSCRIPTIONS_BCM_MESSAGING_EXCEPTION("BCM-1003", "No active subscriptions found", 400),
	
	ACCESS_TOKEN_REMOTE_SYSTEM_EXCEPTION("BCM-4001", "Invalid Access Token", 401),
	REFRESH_TOKEN_REMOTE_SYSTEM_EXCEPTION("BCM-4002", "Invalid Refresh Token", 403),
	UNAUTHORIZED_REMOTE_SYSTEM_EXCEPTION("BCM-4003", "Unauthorized - unable to access remote system", 403),
	INVALID_INPUT_REMOTE_SYSTEM_EXCEPTION("BCM-4004", "Invalid input - remote system invocation failed", 400),
	UNKNOWN_REMOTE_SYSTEM_EXCEPTION("BCM-4005", "An unknown error occured at remote system", 500),
	
	//Lease 
	GET_LEASE_400(Constants.GET_LEASE_ERROR_CODE_BCM_200,Constants.GET_LEASE_CONS,400),
	GET_LEASE_404(Constants.GET_LEASE_ERROR_CODE_BCM_201,Constants.GET_LEASE_CONS,404),
	GET_LEASE_500(Constants.GET_LEASE_ERROR_CODE_BCM_202,Constants.GET_LEASE_CONS,500),
	GET_LEASE_BCM_EXCEPTION(Constants.GET_LEASE_ERROR_CODE_BCM_203,"Unable to get Lease - Remote System Exception",500),
	
	
	GET_LEASE_REFRESH_TOKEN_400(Constants.GET_LEASE_ERROR_CODE_BCM_204,Constants.GET_LEASE_REFRESH_CONS,400),
	GET_LEASE_REFRESH_TOKEN_401(Constants.GET_LEASE_ERROR_CODE_BCM_205,Constants.GET_LEASE_REFRESH_CONS,401),
	GET_LEASE_REFRESH_TOKEN_415(Constants.GET_LEASE_ERROR_CODE_BCM_206,Constants.GET_LEASE_REFRESH_CONS,415),
	GET_LEASE_REFRESH_TOKEN_500(Constants.GET_LEASE_ERROR_CODE_BCM_207,Constants.GET_LEASE_REFRESH_CONS,500),
	GET_LEASE_REFRESH_TOKEN_503(Constants.GET_LEASE_ERROR_CODE_BCM_207,Constants.GET_LEASE_REFRESH_CONS,503),
	
	GET_LEASE_LIST_400(Constants.GET_LEASE_ERROR_CODE_BCM_200,Constants.GET_LEASE_CONS,400),
	GET_LEASE_LIST_404(Constants.GET_LEASE_ERROR_CODE_BCM_201,Constants.GET_LEASE_CONS,404),
	GET_LEASE_LIST_500(Constants.GET_LEASE_ERROR_CODE_BCM_202,Constants.GET_LEASE_CONS,500),
	
	
	GET_LEASE_LIST_REFRESH_TOKEN_400(Constants.GET_LEASE_ERROR_CODE_BCM_204,Constants.GET_LEASE_REFRESH_CONS,400),
	GET_LEASE_LIST_REFRESH_TOKEN_401(Constants.GET_LEASE_ERROR_CODE_BCM_205,Constants.GET_LEASE_REFRESH_CONS,401),
	GET_LEASE_LIST_REFRESH_TOKEN_415(Constants.GET_LEASE_ERROR_CODE_BCM_206,Constants.GET_LEASE_REFRESH_CONS,415),
	GET_LEASE_LIST_REFRESH_TOKEN_500(Constants.GET_LEASE_ERROR_CODE_BCM_207,Constants.GET_LEASE_REFRESH_CONS,500),
	GET_LEASE_LIST_REFRESH_TOKEN_503(Constants.GET_LEASE_ERROR_CODE_BCM_208,Constants.GET_LEASE_REFRESH_CONS,503),
	
	
	GET_LEASE_DETAILS_400(Constants.GET_LEASE_ERROR_CODE_BCM_200,Constants.GET_LEASE_CONS,400),
	GET_LEASE_DETAILS_404(Constants.GET_LEASE_ERROR_CODE_BCM_201,Constants.GET_LEASE_CONS,404),
	GET_LEASE_DETAILS_500(Constants.GET_LEASE_ERROR_CODE_BCM_202,Constants.GET_LEASE_CONS,500),
			  
	GET_LEASE_DETAILS_REFRESH_TOKEN_400(Constants.GET_LEASE_ERROR_CODE_BCM_204,Constants.GET_LEASE_REFRESH_CONS,400),
	GET_LEASE_DETAILS_REFRESH_TOKEN_401(Constants.GET_LEASE_ERROR_CODE_BCM_205,Constants.GET_LEASE_REFRESH_CONS,401),
	GET_LEASE_DETAILS_REFRESH_TOKEN_415(Constants.GET_LEASE_ERROR_CODE_BCM_206,Constants.GET_LEASE_REFRESH_CONS,415),
	GET_LEASE_DETAILS_REFRESH_TOKEN_500(Constants.GET_LEASE_ERROR_CODE_BCM_207,Constants.GET_LEASE_REFRESH_CONS,500),
	GET_LEASE_DETAILS_REFRESH_TOKEN_503(Constants.GET_LEASE_ERROR_CODE_BCM_208,Constants.GET_LEASE_REFRESH_CONS,503),
	
	CREATE_LEASE_400("BCM-209",Constants.CREATE_LEASE_CONS,400),
	CREATE_LEASE_409("BCM-210",Constants.CREATE_LEASE_CONS,409),
	CREATE_LEASE_500("BCM-211",Constants.CREATE_LEASE_CONS,500),
	CREATE_LEASE_BCM_EXCEPTION("BCM-212","Unable to Create Lease - Remote System Exception",500),
	
	
	CREATE_LEASE_REFRESH_TOKEN_400("BCM-213",Constants.CREATE_LEASE_REFRESH_TOKEN_CONS,400),
	CREATE_LEASE_REFRESH_TOKEN_401("BCM-214",Constants.CREATE_LEASE_REFRESH_TOKEN_CONS,401),
	CREATE_LEASE_REFRESH_TOKEN_415("BCM-215",Constants.CREATE_LEASE_REFRESH_TOKEN_CONS,415),
	CREATE_LEASE_REFRESH_TOKEN_500("BCM-216",Constants.CREATE_LEASE_REFRESH_TOKEN_CONS,500),
	CREATE_LEASE_REFRESH_TOKEN_503("BCM-217",Constants.CREATE_LEASE_REFRESH_TOKEN_CONS,503),
	
	
	LEASE_DATA_INVALID("BCM-218", "Invalid Lease Data", 400),
	LEASE_ADDRESS_INVALID("BCM-219", "Invalid address1 data", 400),
	LEASE_ADDRESS_STATE_INVALID("BCM-220", "Invalid state data", 400),
	LEASE_ADDRESS_CITY_INVALID("BCM-221", "Invalid city data", 400),
	LEASE_ADDRESS_ZIP_INVALID("BCM-222", "Invalid zip data", 400),
	LEASE_ALREADY_AVAILABLE("BCM-223", "Lease already exists", 409),
	LEASE_NOT_FOUND("BCM-224", "Lease not found", 404),
	LEASE_RENT_INVALID("BCM-225", "Invalid Rent value", 400),
	LEASE_DUE_DAY_INVALID("BCM-226", "Invalid Due Day, Day should be in 1 to 31", 400),
	
	UPDATE_LEASE_400("BCM-227",Constants.UPDATE_LEASE_CONS,400),
	UPDATE_LEASE_404("BCM-228",Constants.UPDATE_LEASE_CONS,404),
	UPDATE_LEASE_500("BCM-229",Constants.UPDATE_LEASE_CONS,500),
	UPDATE_LEASE_BCM_EXCEPTION("BCM-230","Unable to Update Lease - Remote System Exception",500),
	
	
	UPDATE_LEASE_REFRESH_TOKEN_400("BCM-231",Constants.UPDATE_LEASE_REFRESH_TOKEN_CONS,400),
	UPDATE_LEASE_REFRESH_TOKEN_401("BCM-232",Constants.UPDATE_LEASE_REFRESH_TOKEN_CONS,401),
	UPDATE_LEASE_REFRESH_TOKEN_415("BCM-233",Constants.UPDATE_LEASE_REFRESH_TOKEN_CONS,415),
	UPDATE_LEASE_REFRESH_TOKEN_500("BCM-234",Constants.UPDATE_LEASE_REFRESH_TOKEN_CONS,500),
	UPDATE_LEASE_REFRESH_TOKEN_503("BCM-235",Constants.UPDATE_LEASE_REFRESH_TOKEN_CONS,503),
	
	
	DELETE_LEASE_400("BCM-236",Constants.DELETE_LEASE_CONS,400),
	DELETE_LEASE_404("BCM-237",Constants.DELETE_LEASE_CONS,404),
	DELETE_LEASE_500("BCM-238",Constants.DELETE_LEASE_CONS,500),
	DELETE_LEASE_BCM_EXCEPTION("BCM-239","Unable to Delete Lease - Remote System Exception",500),
	
	
	DELETE_LEASE_REFRESH_TOKEN_400("BCM-240",Constants.DELETE_LEASE_REFRESH_TOKEN_CONS,400),
	DELETE_LEASE_REFRESH_TOKEN_401("BCM-241",Constants.DELETE_LEASE_REFRESH_TOKEN_CONS,401),
	DELETE_LEASE_REFRESH_TOKEN_415("BCM-242",Constants.DELETE_LEASE_REFRESH_TOKEN_CONS,415),
	DELETE_LEASE_REFRESH_TOKEN_500("BCM-243",Constants.DELETE_LEASE_REFRESH_TOKEN_CONS,500),
	DELETE_LEASE_REFRESH_TOKEN_503("BCM-244",Constants.DELETE_LEASE_REFRESH_TOKEN_CONS,503),
	
	//Same Response for all Lease Calls	
	GET_LEASE_REFRESH_TOKEN_BCM_EXCEPTION(Constants.GET_LEASE_ERROR_CODE_BCM_245, Constants.GET_LEASE_REFRESH_TOKEN_CONS,500),
	GET_LEASE_LIST_REFRESH_TOKEN_BCM_EXCEPTION(Constants.GET_LEASE_ERROR_CODE_BCM_245,Constants.GET_LEASE_REFRESH_TOKEN_CONS,500),
	GET_LEASE_DETAILS_REFRESH_TOKEN_BCM_EXCEPTION(Constants.GET_LEASE_ERROR_CODE_BCM_245,Constants.GET_LEASE_REFRESH_TOKEN_CONS,500),
	
	CREATE_LEASE_REFRESH_TOKEN_BCM_EXCEPTION("BCM-246","Unable to Create Refresh Token while creating lease - Remote System Exception",500),
	UPDATE_LEASE_REFRESH_TOKEN_BCM_EXCEPTION("BCM-247","Unable to Create Refresh Token while updating Lease - Remote System Exception",500),
	DELETE_LEASE_REFRESH_TOKEN_BCM_EXCEPTION("BCM-248","Unable to Create Refresh Token while deleting Lease - Remote System Exception",500),
	
	
	GET_LEASE_401("BCM-249",Constants.GET_LEASE_CONS,401),
	CREATE_LEASE_401("BCM-250",Constants.CREATE_LEASE_CONS,401),
	UPDATE_LEASE_401("BCM-251",Constants.UPDATE_LEASE_CONS,401),
	DELETE_LEASE_401("BCM-252",Constants.DELETE_LEASE_CONS,401),
	
	GET_LEASE_ORDERS_LIST_400("BCM-253",Constants.GET_LEASE_ORDERS_LIST_CONS,400),
	GET_LEASE_ORDERS_LIST_500("BCM-254",Constants.PAYMENT_ACCOUNT_CONS,500),
	GET_LEASE_ORDERS_LIST_BCM_EXCEPTION("BCM-255","Unable to Get Lease Orders - Remote System Exception",500),

	GET_LEASE_ORDERS_LIST_REFRESH_TOKEN_400("BCM-256",Constants.GET_LEASE_ORDERS_LIST_REFRESH_TOKEN_CONS,400),
	GET_LEASE_ORDERS_LIST_REFRESH_TOKEN_401("BCM-257",Constants.GET_LEASE_ORDERS_LIST_REFRESH_TOKEN_CONS,401),
	GET_LEASE_ORDERS_LIST_REFRESH_TOKEN_415("BCM-258",Constants.GET_LEASE_ORDERS_LIST_REFRESH_TOKEN_CONS,415),
	GET_LEASE_ORDERS_LIST_REFRESH_TOKEN_500("BCM-259",Constants.GET_LEASE_ORDERS_LIST_REFRESH_TOKEN_CONS,500),
	GET_LEASE_ORDERS_LIST_REFRESH_TOKEN_503("BCM-260",Constants.GET_LEASE_ORDERS_LIST_REFRESH_TOKEN_CONS,503),
	GET_LEASE_ORDERS_LIST_REFRESH_TOKEN_BCM_EXCEPTION("BCM-261","Unable to Create Refresh Token while getting Lease Orders - Remote System Exception",500),
	//Plaid
	PLAID_PUBLIC_TOKEN_INVALID("BCM-300", "Invalid Public Token", 400),
	
	
	PAYMENT_ACCOUNT_400("BCM-301",Constants.PAYMENT_ACCOUNT_CONS,400),
	PAYMENT_ACCOUNT_500("BCM-302",Constants.PAYMENT_ACCOUNT_CONS,500),
	PAYMENT_ACCOUNT_BCM_EXCEPTION("BCM-303","Unable to Create Payment Account - Remote System Exception",500),
	
	PAYMENT_ACCOUNT_REFRESH_TOKEN_400("BCM-304",Constants.PAYMENT_ACCOUNT_REFRESH_TOKEN_CONS,400),
	PAYMENT_ACCOUNT_REFRESH_TOKEN_401("BCM-305",Constants.PAYMENT_ACCOUNT_REFRESH_TOKEN_CONS,401),
	PAYMENT_ACCOUNT_REFRESH_TOKEN_415("BCM-306",Constants.PAYMENT_ACCOUNT_REFRESH_TOKEN_CONS,415),
	PAYMENT_ACCOUNT_REFRESH_TOKEN_500("BCM-307",Constants.PAYMENT_ACCOUNT_REFRESH_TOKEN_CONS,500),
	PAYMENT_ACCOUNT_REFRESH_TOKEN_503("BCM-308",Constants.PAYMENT_ACCOUNT_REFRESH_TOKEN_CONS,503),
	PAYMENT_ACCOUNT_REFRESH_TOKEN_BCM_EXCEPTION("BCM-309","Unable to Create Refresh Token while Creating Payment Account - Remote System Exception",500),
	PAYMENT_ACCOUNT_ALREADY_AVAILABLE("BCM-310","Payment Account Already Exists",409),
	
	GET_PAYMENT_ACCOUNT_500("BCM-311",Constants.GET_PAYMENT_ACCOUNT_CONS,500),
	GET_PAYMENT_ACCOUNT_BCM_EXCEPTION("BCM-312","Unable to get Payment Account - Remote System Exception",500),
	
	GET_PAYMENT_ACCOUNT_REFRESH_TOKEN_400("BCM-313",Constants.GET_PAYMENT_ACCOUNT_REFRESH_TOKEN_CONS,400),
	GET_PAYMENT_ACCOUNT_REFRESH_TOKEN_401("BCM-314",Constants.GET_PAYMENT_ACCOUNT_REFRESH_TOKEN_CONS,401),
	GET_PAYMENT_ACCOUNT_REFRESH_TOKEN_415("BCM-315",Constants.GET_PAYMENT_ACCOUNT_REFRESH_TOKEN_CONS,415),
	GET_PAYMENT_ACCOUNT_REFRESH_TOKEN_500("BCM-316",Constants.GET_PAYMENT_ACCOUNT_REFRESH_TOKEN_CONS,500),
	GET_PAYMENT_ACCOUNT_REFRESH_TOKEN_503("BCM-317",Constants.GET_PAYMENT_ACCOUNT_REFRESH_TOKEN_CONS,503),
	GET_PAYMENT_ACCOUNT_REFRESH_TOKEN_BCM_EXCEPTION("BCM-318","Unable to Create Refresh Token while getting Payment Account - Remote System Exception",500),
	
	PAYMENT_ACCOUNT_401("BCM-319",Constants.PAYMENT_ACCOUNT_CONS,401),
	GET_PAYMENT_ACCOUNT_401("BCM-320",Constants.GET_PAYMENT_ACCOUNT_CONS,401),
	PAYMENT_ACCOUNT_409("BCM-321","Payment Account Already Exists",409),
	PAYMENT_ACCOUNT_404("BCM-322","Payment Account not Found",404),
	GET_PAYMENT_ACCOUNT_400("BCM-323",Constants.GET_PAYMENT_ACCOUNT_CONS,400),
		//TransactionFinder
	TRANSACTION_FINDER_AMOUNT_RENT("BCM-400", "Invalid Amount", 400),
	TRANSACTION_FINDER_DUE_DAY("BCM-401", "Invalid Due Day", 400),
	TRANSACTION_FINDER_PAYMENT_ACC("BCM-402", "Payment Account not found", 404),
	TRANSACTION_FINDER_LEASE("BCM-403", "Consumer Lease not found", 404),
	TRANSACTION_FINDER_ALREADY_AVAILABLE("BCM-404", "The consumer lease provided already has active transaction finder", 409),
	
	CREATE_TRX_FINDER_400("BCM-406",Constants.CREATE_TRX_FINDER_CONS,400),
	CREATE_TRX_FINDER_404("BCM-407",Constants.CREATE_TRX_FINDER_CONS,404),
	CREATE_TRX_FINDER_500("BCM-408",Constants.CREATE_TRX_FINDER_CONS,500),
	CREATE_TRX_FINDER_BCM_EXCEPTION("BCM-409","Unable to Create Transaction Finder - Remote System Exception",500),

	
	CREATE_TRX_FINDER_REFRESH_TOKEN_400("BCM-410",Constants.CREATE_TRX_FINDER_REFRESH_TOKEN_CONS,400),
	CREATE_TRX_FINDER_REFRESH_TOKEN_401("BCM-411",Constants.CREATE_TRX_FINDER_REFRESH_TOKEN_CONS,401),
	CREATE_TRX_FINDER_REFRESH_TOKEN_415("BCM-416",Constants.CREATE_TRX_FINDER_REFRESH_TOKEN_CONS,415),
	CREATE_TRX_FINDER_REFRESH_TOKEN_500("BCM-417",Constants.CREATE_TRX_FINDER_REFRESH_TOKEN_CONS,500),
	CREATE_TRX_FINDER_REFRESH_TOKEN_503("BCM-418",Constants.CREATE_TRX_FINDER_REFRESH_TOKEN_CONS,503),
	CREATE_TRX_FINDER_REFRESH_TOKEN_BCM_EXCEPTION("BCM-419","Unable to Create Refresh Token while Creating Transaction Finder - Remote System Exception",500),
	PLAID_CONNECTION_INVALID("BCM-420", "Invalid Contract url data", 400),
	
	SEARCH_TRX_FINDER_400("BCM-421",Constants.SEARCH_TRX_FINDER_CONS,400),
	SEARCH_TRX_FINDER_404("BCM-422",Constants.SEARCH_TRX_FINDER_CONS,404),
	SEARCH_TRX_FINDER_500("BCM-423",Constants.SEARCH_TRX_FINDER_CONS,500),
	SEARCH_TRX_FINDER_BCM_EXCEPTION("BCM-424","Transaction Finder has been Created. Unable to Search Transactions - Remote System Exception",500),
	
	SEARCH_TRX_FINDER("BCM-425",Constants.SEARCH_TRX_FINDER_REFRESH_TOKEN_CONS,400),
	SEARCH_TRX_FINDER_REFRESH_TOKEN_401("BCM-426",Constants.SEARCH_TRX_FINDER_REFRESH_TOKEN_CONS,401),
	SEARCH_TRX_FINDER_REFRESH_TOKEN_415("BCM-427",Constants.SEARCH_TRX_FINDER_REFRESH_TOKEN_CONS,415),
	SEARCH_TRX_FINDER_REFRESH_TOKEN_500("BCM-428",Constants.SEARCH_TRX_FINDER_REFRESH_TOKEN_CONS,500),
	SEARCH_TRX_FINDER_REFRESH_TOKEN_503("BCM-429",Constants.SEARCH_TRX_FINDER_REFRESH_TOKEN_CONS,503),
	SEARCH_TRX_FINDER_REFRESH_TOKEN_BCM_EXCEPTION("BCM-430","Transaction Finder has been Created. Unable to Create Refresh Token while searching for transactions - Remote System Exception",500),
	
	CREATE_TRX_FINDER_401("BCM-431",Constants.CREATE_TRX_FINDER_CONS,401),
	SEARCH_TRX_FINDER_401("BCM-432",Constants.SEARCH_TRX_FINDER_CONS,401),
	UPDATE_TRX_FINDER_401("BCM-433",Constants.UPADATE_TRX_FINDER_CONS,401),
	UPDATE_TRX_FINDER_BCM_EXCEPTION("BCM-434","Unable to Update Transaction Finder - Remote System Exception",500),
	
	SEARCH_TRX_ID_400("BCM-435",Constants.SEARCH_TRX_ID_CONS,400),
	SEARCH_TRX_ID_404("BCM-436",Constants.SEARCH_TRX_ID_CONS,404),
	SEARCH_TRX_ID_500("BCM-437",Constants.SEARCH_TRX_ID_CONS,500),
	SEARCH_TRX_ID_REFRESH_TOKEN_401("BCM-438",Constants.SEARCH_TRX_ID_REFRESH_TOKEN_CONS,401),
	SEARCH_TRX_ID_REFRESH_TOKEN_415("BCM-439",Constants.SEARCH_TRX_ID_REFRESH_TOKEN_CONS,415),
	SEARCH_TRX_ID_REFRESH_TOKEN_500("BCM-440",Constants.SEARCH_TRX_ID_REFRESH_TOKEN_CONS,500),
	SEARCH_TRX_ID_REFRESH_TOKEN_503("BCM-441",Constants.SEARCH_TRX_ID_REFRESH_TOKEN_CONS,503),
	SEARCH_TRX_ID_REFRESH_TOKEN_BCM_EXCEPTION("BCM-442","Unable to Create Refresh Token while searching for transactions - Remote System Exception",500),
	SEARCH_TRX_ID_401("BCM-443",Constants.SEARCH_TRX_ID_CONS,401),
	
	MATCH_TRX_FINDER_400("BCM-500",Constants.MATCH_TRX_FINDER_CONS,400),
	MATCH_TRX_FINDER_404("BCM-501",Constants.MATCH_TRX_FINDER_CONS,404),
	
	MATCH_TRX_FINDER_500("BCM-502",Constants.MATCH_TRX_FINDER_CONS,500),
	MATCH_TRX_FINDER_BCM_EXCEPTION("BCM-503","Error while Matching Transactions - Remote System Exception",500),

	MATCH_TRX_FINDER("BCM-504",Constants.MATCH_TRX_FINDER_REFRESH_TOKEN_CONS,400),
	MATCH_TRX_FINDER_REFRESH_TOKEN_401("BCM-505",Constants.MATCH_TRX_FINDER_REFRESH_TOKEN_CONS,401),
	MATCH_TRX_FINDER_REFRESH_TOKEN_415("BCM-506",Constants.MATCH_TRX_FINDER_REFRESH_TOKEN_CONS,415),
	MATCH_TRX_FINDER_REFRESH_TOKEN_500("BCM-507",Constants.MATCH_TRX_FINDER_REFRESH_TOKEN_CONS,500),
	MATCH_TRX_FINDER_REFRESH_TOKEN_503("BCM-508",Constants.MATCH_TRX_FINDER_REFRESH_TOKEN_CONS,503),
	MATCH_TRX_FINDER_REFRESH_TOKEN_BCM_EXCEPTION("BCM-509","Error while Matching Transactions. Unable to Create Refresh Token while searching for transactions - Remote System Exception",500),
	
	MATCH_TRX_FINDER_NO_RECORDS("BCM-510","No transaction Finder Id Found",404),
	MATCH_TRX_FINDER_409("BCM-511",Constants.MATCH_TRX_FINDER_CONS,409),
	MATCH_TRX_FINDER_401("BCM-512",Constants.MATCH_TRX_FINDER_CONS,401),
	UPDATE_TRX_FINDER_500("BCM-513", Constants.UPADATE_TRX_FINDER_CONS, 500),	

	GET_TRX_FINDER_404("BCM-514",Constants.GET_TRX_FINDER_CONS,404),
	GET_TRX_FINDER_500("BCM-515",Constants.GET_TRX_FINDER_CONS,500),
	GET_TRX_FINDER_BCM_EXCEPTION("BCM-516","Unable to Create Transaction Finder - Remote System Exception",500),

	GET_TRX_FINDER_REFRESH_TOKEN_400("BCM-517",Constants.GET_TRX_FINDER_REFRESH_TOKEN_CONS,400),
	GET_TRX_FINDER_REFRESH_TOKEN_401("BCM-518",Constants.GET_TRX_FINDER_REFRESH_TOKEN_CONS,401),
	GET_TRX_FINDER_REFRESH_TOKEN_415("BCM-519",Constants.GET_TRX_FINDER_REFRESH_TOKEN_CONS,415),
	GET_TRX_FINDER_REFRESH_TOKEN_500("BCM-520",Constants.GET_TRX_FINDER_REFRESH_TOKEN_CONS,500),
	GET_TRX_FINDER_REFRESH_TOKEN_503("BCM-521",Constants.GET_TRX_FINDER_REFRESH_TOKEN_CONS,503),
	GET_TRX_FINDER_REFRESH_TOKEN_BCM_EXCEPTION("BCM-522","Unable to Create Refresh Token while Getting Transaction Finder - Remote System Exception",500),
	
	TRX_FINDER_NOT_FOUND("BCM-523","Transaction Finder not Found",404),
	
	GET_ALL_UTILITIES_BCM_EXCEPTION("BCM-600","Error while Getting All Utilities",500),
	GET_ALL_UTILITIES_500("BCM-601","Error while Getting All Utilities - Remote System Exception",500),
	
	GET_ALL_UTILITIES_REFRESH_TOKEN_401("BCM-602",Constants.GET_ALL_UTILITIES_REFRESH_TOKEN_CONS,401),
	GET_ALL_UTILITIES_REFRESH_TOKEN_415("BCM-603",Constants.GET_ALL_UTILITIES_REFRESH_TOKEN_CONS,415),
	GET_ALL_UTILITIES_REFRESH_TOKEN_500("BCM-604",Constants.GET_ALL_UTILITIES_REFRESH_TOKEN_CONS,500),
	GET_ALL_UTILITIES_REFRESH_TOKEN_503("BCM-605",Constants.GET_ALL_UTILITIES_REFRESH_TOKEN_CONS,503),
	GET_ALL_UTILITIES_REFRESH_TOKEN_BCM_EXCEPTION("BCM-606","Error while Getting All Utilities. Unable to Generate access token for the user - Remote System Exception",500),
	
	
	GET_UTILBY_TRDID_404("BCM-607","Error while Getting Utility By Trade Line Id",404),
	GET_UTILBY_TRDID_500("BCM-608","Error while Getting Utility By Trade Line Id ",500),
	GET_UTILBY_TRDID_BCM_EXCEPTION("BCM-609","Error while Getting Utility By Trade Line Id - Remote System Exception",500),
	
	GET_UTILBY_TRDID_REFRESH_TOKEN_401("BCM-610",Constants.GET_UTILBY_TRDID_REFRESH_TOKEN_CONS,401),
	GET_UTILBY_TRDID_REFRESH_TOKEN_415("BCM-611",Constants.GET_UTILBY_TRDID_REFRESH_TOKEN_CONS,415),
	GET_UTILBY_TRDID_REFRESH_TOKEN_500("BCM-612",Constants.GET_UTILBY_TRDID_REFRESH_TOKEN_CONS,500),
	GET_UTILBY_TRDID_REFRESH_TOKEN_503("BCM-613",Constants.GET_UTILBY_TRDID_REFRESH_TOKEN_CONS,503),
	GET_UTILBY_TRDID_REFRESH_TOKEN_BCM_EXCEPTION("BCM-614","Error while Getting Utility Details. Unable to Generate access token for the user - Remote System Exception",500),
	
	PATCH_UTIL_400("BCM-615",Constants.PATCH_UTIL_CONS,404),
	PATCH_UTIL_404("BCM-616",Constants.PATCH_UTIL_CONS,404),
	PATCH_UTIL_500("BCM-617",Constants.PATCH_UTIL_CONS,404),
	PATCH_UTIL_BCM_EXCEPTION("BCM-618","Error while updating Utility Status - Remote System Exception",500),	
	
	PATCH_UTIL_REFRESH_TOKEN_401("BCM-619",Constants.PATCH_UTIL_REFRESH_TOKEN_CONS,401),
	PATCH_UTIL_REFRESH_TOKEN_415("BCM-620",Constants.PATCH_UTIL_REFRESH_TOKEN_CONS,415),
	PATCH_UTIL_REFRESH_TOKEN_500("BCM-621",Constants.PATCH_UTIL_REFRESH_TOKEN_CONS,500),
	PATCH_UTIL_REFRESH_TOKEN_503("BCM-622",Constants.PATCH_UTIL_REFRESH_TOKEN_CONS,503),
	PATCH_UTIL_REFRESH_TOKEN_BCM_EXCEPTION("BCM-623","Error while Updating Utility Status. Unable to Generate access token for the user - Remote System Exception",500),
	PATCH_UTIL_INVALID_UTIL_STATUS("BCM-624","Invalid Utility Status",400),
	PATCH_UTIL_INVALID_UTIL_TYPE("BCM-625","Utility Type Not Found",400),
	
	GET_ALL_UTILITIES_401("BCM-626","Error while Getting All Utilities",401),
	GET_UTILBY_TRDID_401("BCM-627","Error while Getting Utility By Trade Line Id",401),
	PATCH_UTIL_401("BCM-628","EError while Updating Utility Status",401),	
	
	PAYMENT_ACCOUNT_NOT_FOUND("BCM-700","Payment Account Not Found in BCM",404),
	PLAID_RECONNECTION_404("BCM-701",Constants.PLAID_RECONNECTION_CONS,404),
	PLAID_RECONNECTION_400("BCM-702",Constants.PLAID_RECONNECTION_CONS,400),
	PLAID_RECONNECTION_500("BCM-704",Constants.PLAID_RECONNECTION_CONS,500),
	PLAID_RECONNECTION_503("BCM-705",Constants.PLAID_RECONNECTION_CONS,503),
	PLAID_RECONNECTION_BCM_EXCEPTION("BCM-706","Error while Reconnecting to Plaid - Remote System Exception",503),
	
	PLAID_RECONNECTION_REFRESH_TOKEN_401("BCM-707",Constants.PLAID_RECONNECTION_REFRESH_TOKEN_CONS,401),
	PLAID_RECONNECTION_REFRESH_TOKEN_415("BCM-708",Constants.PLAID_RECONNECTION_REFRESH_TOKEN_CONS,415),
	PLAID_RECONNECTION_REFRESH_TOKEN_500("BCM-709",Constants.PLAID_RECONNECTION_REFRESH_TOKEN_CONS,500),
	PLAID_RECONNECTION_REFRESH_TOKEN_503("BCM-710",Constants.PLAID_RECONNECTION_REFRESH_TOKEN_CONS,503),
	PLAID_RECONNECTION_REFRESH_TOKEN_BCM_EXCEPTION("BCM-711","Error while Reconnecting to Plaid. Unable to Generate access token for the user - Remote System Exception",500),
	
	PLAID_RECONNECTION_PATCH_404("BCM-701",Constants.PLAID_RECONNECTION_PATCH_CONS,404),
	PLAID_RECONNECTION_PATCH_400("BCM-702",Constants.PLAID_RECONNECTION_PATCH_CONS,400),
	PLAID_RECONNECTION_PATCH_401("BCM-703",Constants.PLAID_RECONNECTION_PATCH_CONS,401),
	PLAID_RECONNECTION_PATCH_500("BCM-704",Constants.PLAID_RECONNECTION_PATCH_CONS,500),
	PLAID_RECONNECTION_PATCH_503("BCM-705",Constants.PLAID_RECONNECTION_PATCH_CONS,503),
	PLAID_RECONNECTION_PATCH_BCM_EXCEPTION("BCM-706","Error while Reconnecting to Plaid - Remote System Exception",503),
	
	PLAID_RECONNECTION_PATCH_REFRESH_TOKEN_401("BCM-707",Constants.PLAID_RECONNECTION_PATCH_REFRESH_TOKEN_CONS,401),
	PLAID_RECONNECTION_PATCH_REFRESH_TOKEN_415("BCM-708",Constants.PLAID_RECONNECTION_PATCH_REFRESH_TOKEN_CONS,415),
	PLAID_RECONNECTION_PATCH_REFRESH_TOKEN_500("BCM-709",Constants.PLAID_RECONNECTION_PATCH_REFRESH_TOKEN_CONS,500),
	PLAID_RECONNECTION_PATCH_REFRESH_TOKEN_503("BCM-710",Constants.PLAID_RECONNECTION_PATCH_REFRESH_TOKEN_CONS,503),
	PLAID_RECONNECTION_PATCH_REFRESH_TOKEN_BCM_EXCEPTION("BCM-711","Error while Reconnecting to Plaid. Unable to Generate access token for the user - Remote System Exception",500), 
	JOB_EXCEPTION("BCM-800","Job Exception",500),
	JOB_NOT_FOUND("BCM-801","Job Not Found",404),
	JOB_ALREADY_EXISTS("BCM-802","Job Already Exists",409),
	JOB_INTERRUPTED("BCM-802","Job Interrupted",500),
	MATCHING_JOB_NOT_FOUND("BCM-803","Job Not Found",404),
	FAILED_DEPROVISION_NOT_SAVE("BCM-804","Error while Saving Failed Deprovision records",403),
	
	GET_UTILITY_ORDERS_LIST_400("BCM-900",Constants.GET_UTILITY_ORDERS_LIST_CONS,400),
	GET_UTILITY_ORDERS_LIST_500("BCM-901",Constants.GET_UTILITY_ORDERS_LIST_CONS,500),

	GET_UTILITY_ORDERS_LIST_REFRESH_TOKEN_400("BCM-902",Constants.GET_UTILITY_ORDERS_LIST_REFRESH_TOKEN_CONS,400),
	GET_UTILITY_ORDERS_LIST_REFRESH_TOKEN_401("BCM-903",Constants.GET_UTILITY_ORDERS_LIST_REFRESH_TOKEN_CONS,401),
	GET_UTILITY_ORDERS_LISTT_REFRESH_TOKEN_415("BCM-904",Constants.GET_UTILITY_ORDERS_LIST_REFRESH_TOKEN_CONS,415),
	GET_UTILITY_ORDERS_LIST_REFRESH_TOKEN_500("BCM-905",Constants.GET_UTILITY_ORDERS_LIST_REFRESH_TOKEN_CONS,500),
	GET_UTILITY_ORDERS_LIST_REFRESH_TOKEN_503("BCM-906",Constants.GET_UTILITY_ORDERS_LIST_REFRESH_TOKEN_CONS,503),
	GET_UTILITY_ORDERS_LIST_REFRESH_TOKEN_BCM_EXCEPTION("BCM-907",Constants.GET_UTILITY_ORDERS_LIST_REFRESH_TOKEN_CONS+ "- Remote System Exception",500),
	GET_UTILITY_ORDERS_LIST_BCM_EXCEPTION("BCM-908", Constants.GET_UTILITY_ORDERS_LIST_CONS +" - Remote System Exception",500),
	;

	private String code;
	private String description;
	private Integer httpStatusCode;

	BCMModuleExceptionEnum(String code, String description, Integer httpStatusCode) {
		this.code = code;
		this.description = description;
		this.httpStatusCode = httpStatusCode;
	}

	public String getCode() {
		return code;
	}

	public String getDescription() {
		return description;
	}

	public Integer getHttpStatusCode() {
		return httpStatusCode;
	}
	
	private static class Constants {
        public static final String PATCH_UTIL_REFRESH_TOKEN_CONS = "Error while Updating Utility Status. Unable to Generate access token for the user";
        public static final String PATCH_UTIL_CONS = "Error while Updating Utility Status";
        public static final String GET_UTILBY_TRDID_REFRESH_TOKEN_CONS = "Error while Getting Utility Details. Unable to Generate access token for the user";
        public static final String GET_ALL_UTILITIES_REFRESH_TOKEN_CONS = "Error while Getting All Utilities. Unable to Generate access token for the user";
    	public static final String MATCH_TRX_FINDER_REFRESH_TOKEN_CONS = "Error while Matching Transactions. Unable to Create Refresh Token while searching for transactions";
    	public static final String MATCH_TRX_FINDER_CONS = "Error while Matching Transactions";
    	public static final String SEARCH_TRX_FINDER_REFRESH_TOKEN_CONS = "Transaction Finder has been Created. Unable to Create Refresh Token while searching for transactions";
    	public static final String SEARCH_TRX_FINDER_CONS = "Transaction Finder has been Created. Unable to Search Transactions";
    	public static final String CREATE_TRX_FINDER_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while Creating Transaction Finder";
    	public static final String CREATE_TRX_FINDER_CONS = "Unable to Create Transaction Finder";
    	public static final String GET_PAYMENT_ACCOUNT_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while getting Payment Account";
    	public static final String PAYMENT_ACCOUNT_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while Creating Payment Account";
    	public static final String PAYMENT_ACCOUNT_CONS = "Unable to Create Payment Account";
    	public static final String DELETE_LEASE_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while deleting Lease";
    	public static final String DELETE_LEASE_CONS = "Unable to Delete Lease";
    	public static final String UPDATE_LEASE_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while updating Lease";
    	public static final String UPDATE_LEASE_CONS = "Unable to Update Lease";
    	public static final String CREATE_LEASE_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while Creating Lease";
    	public static final String CREATE_LEASE_CONS = "Unable to Create Lease";
    	public static final String GET_LEASE_REFRESH_CONS = "Unable to Create Refresh Token while invoking get Lease";
    	public static final String GET_LEASE_CONS = "Unable to get Lease";
    	public static final String SUBSCRIPTION_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while Creating Subscription";
    	public static final String SUBSCRIPTION_CONS = "Unable to Subscription while creating Tenant User";
    	public static final String PATCH_TENANT_USER_CONS = "Unable to Update DOB while creating Tenant User";
    	public static final String CREATE_TENANT_CONS = "Unable to Create Tenant User";
    	public static final String CREATE_TENANT_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while Creating tenant User";
    	public static final String PARTNER_TOKEN_CONS = "Unable to Create Partner Token while Creating tenant User";
    	public static final String ACCESS_TOKEN_CONS = "Unable to Create Access Token while Creating tenant User";
    	public static final String UPADATE_TRX_FINDER_CONS = "Unable to Upadate Transaction Finder";
    	public static final String PLAID_RECONNECTION_CONS = "Unable to Reconnect Plaid";
    	public static final String PLAID_RECONNECTION_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while Reconnecting to Plaid";
    	public static final String PLAID_RECONNECTION_PATCH_CONS = "Unable to Reconnect Plaid";
    	public static final String PLAID_RECONNECTION_PATCH_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while Reconnecting to Plaid";
    	public static final String GET_SUBSCRIPTIONS_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while validating Subscription";
    	public static final String GET_SUBSCRIPTIONS_CONS = "Unable to validate Subscription";
    	public static final String SEARCH_TRX_ID_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while searching for transactions";
    	public static final String SEARCH_TRX_ID_CONS = "Unable to Search Transactions";
    	public static final String TENANT_USER_NOT_CREATED = "Tenant User Account not done successfully";
    	public static final String GET_LEASE_ORDERS_LIST_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while getting Lease Orders";
    	public static final String GET_LEASE_ORDERS_LIST_CONS = "Unable to get Lease orders";
    	public static final String GET_LEASE_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while getting lease - Remote System Exception";
    	public static final String GET_LEASE_ERROR_CODE_BCM_200 = "BCM-200";
    	public static final String GET_LEASE_ERROR_CODE_BCM_201 = "BCM-201";
    	public static final String GET_LEASE_ERROR_CODE_BCM_202 = "BCM-202";
    	public static final String GET_LEASE_ERROR_CODE_BCM_203 = "BCM-203";
    	public static final String GET_LEASE_ERROR_CODE_BCM_204 = "BCM-204";
    	public static final String GET_LEASE_ERROR_CODE_BCM_205 = "BCM-205";
    	public static final String GET_LEASE_ERROR_CODE_BCM_206 = "BCM-206";
    	public static final String GET_LEASE_ERROR_CODE_BCM_207 = "BCM-207";
    	public static final String GET_LEASE_ERROR_CODE_BCM_208 = "BCM-208";
    	public static final String GET_LEASE_ERROR_CODE_BCM_245 = "BCM-245";
    	public static final String GET_PAYMENT_ACCOUNT_CONS = "Unable to Get Payment Account";
    	public static final String CUSTOMER_MASTER_NOT_FOUND_CONS = "Unable to fetch Customer Data";
    	public static final String GET_UTILITY_ORDERS_LIST_CONS = "Unable to getLease orders";
    	public static final String GET_UTILITY_ORDERS_LIST_REFRESH_TOKEN_CONS = "Unable to getLease orders";
    	public static final String GET_TRX_FINDER_CONS = "Unable to Get Transaction Finder Details";
    	public static final String GET_TRX_FINDER_REFRESH_TOKEN_CONS = "Unable to Create Refresh Token while getting Transaction Finder details";

    } 

}
